"""MMLU, 5-shot multiple choice (57 subjects). Frozen from pinned lm-eval
0.4.8; fidelity-gated 2026-08-12. Flat group: stock nests subjects under 4
category groups, but the headline `mmlu` number is the size-weighted micro
average over all docs either way (category subaggregates were never used by
the manuscript). num_fewshot comes from the cell (BENCH pins 5).
SUBJECTS rows: (task_name, dataset_name, description) -- extracted verbatim
from the pinned per-subject yamls."""

SUBJECTS = [
    ('mmlu_abstract_algebra', 'abstract_algebra',
     'The following are multiple choice questions (with answers) about abstract algebra.\n\n'),
    ('mmlu_anatomy', 'anatomy',
     'The following are multiple choice questions (with answers) about anatomy.\n\n'),
    ('mmlu_astronomy', 'astronomy',
     'The following are multiple choice questions (with answers) about astronomy.\n\n'),
    ('mmlu_business_ethics', 'business_ethics',
     'The following are multiple choice questions (with answers) about business ethics.\n\n'),
    ('mmlu_clinical_knowledge', 'clinical_knowledge',
     'The following are multiple choice questions (with answers) about clinical knowledge.\n\n'),
    ('mmlu_college_biology', 'college_biology',
     'The following are multiple choice questions (with answers) about college biology.\n\n'),
    ('mmlu_college_chemistry', 'college_chemistry',
     'The following are multiple choice questions (with answers) about college chemistry.\n\n'),
    ('mmlu_college_computer_science', 'college_computer_science',
     'The following are multiple choice questions (with answers) about college computer science.\n\n'),
    ('mmlu_college_mathematics', 'college_mathematics',
     'The following are multiple choice questions (with answers) about college mathematics.\n\n'),
    ('mmlu_college_medicine', 'college_medicine',
     'The following are multiple choice questions (with answers) about college medicine.\n\n'),
    ('mmlu_college_physics', 'college_physics',
     'The following are multiple choice questions (with answers) about college physics.\n\n'),
    ('mmlu_computer_security', 'computer_security',
     'The following are multiple choice questions (with answers) about computer security.\n\n'),
    ('mmlu_conceptual_physics', 'conceptual_physics',
     'The following are multiple choice questions (with answers) about conceptual physics.\n\n'),
    ('mmlu_econometrics', 'econometrics',
     'The following are multiple choice questions (with answers) about econometrics.\n\n'),
    ('mmlu_electrical_engineering', 'electrical_engineering',
     'The following are multiple choice questions (with answers) about electrical engineering.\n\n'),
    ('mmlu_elementary_mathematics', 'elementary_mathematics',
     'The following are multiple choice questions (with answers) about elementary mathematics.\n\n'),
    ('mmlu_formal_logic', 'formal_logic',
     'The following are multiple choice questions (with answers) about formal logic.\n\n'),
    ('mmlu_global_facts', 'global_facts',
     'The following are multiple choice questions (with answers) about global facts.\n\n'),
    ('mmlu_high_school_biology', 'high_school_biology',
     'The following are multiple choice questions (with answers) about high school biology.\n\n'),
    ('mmlu_high_school_chemistry', 'high_school_chemistry',
     'The following are multiple choice questions (with answers) about high school chemistry.\n\n'),
    ('mmlu_high_school_computer_science', 'high_school_computer_science',
     'The following are multiple choice questions (with answers) about high school computer science.\n\n'),
    ('mmlu_high_school_european_history', 'high_school_european_history',
     'The following are multiple choice questions (with answers) about high school european history.\n\n'),
    ('mmlu_high_school_geography', 'high_school_geography',
     'The following are multiple choice questions (with answers) about high school geography.\n\n'),
    ('mmlu_high_school_government_and_politics', 'high_school_government_and_politics',
     'The following are multiple choice questions (with answers) about high school government and politics.\n\n'),
    ('mmlu_high_school_macroeconomics', 'high_school_macroeconomics',
     'The following are multiple choice questions (with answers) about high school macroeconomics.\n\n'),
    ('mmlu_high_school_mathematics', 'high_school_mathematics',
     'The following are multiple choice questions (with answers) about high school mathematics.\n\n'),
    ('mmlu_high_school_microeconomics', 'high_school_microeconomics',
     'The following are multiple choice questions (with answers) about high school microeconomics.\n\n'),
    ('mmlu_high_school_physics', 'high_school_physics',
     'The following are multiple choice questions (with answers) about high school physics.\n\n'),
    ('mmlu_high_school_psychology', 'high_school_psychology',
     'The following are multiple choice questions (with answers) about high school psychology.\n\n'),
    ('mmlu_high_school_statistics', 'high_school_statistics',
     'The following are multiple choice questions (with answers) about high school statistics.\n\n'),
    ('mmlu_high_school_us_history', 'high_school_us_history',
     'The following are multiple choice questions (with answers) about high school us history.\n\n'),
    ('mmlu_high_school_world_history', 'high_school_world_history',
     'The following are multiple choice questions (with answers) about high school world history.\n\n'),
    ('mmlu_human_aging', 'human_aging',
     'The following are multiple choice questions (with answers) about human aging.\n\n'),
    ('mmlu_human_sexuality', 'human_sexuality',
     'The following are multiple choice questions (with answers) about human sexuality.\n\n'),
    ('mmlu_international_law', 'international_law',
     'The following are multiple choice questions (with answers) about international law.\n\n'),
    ('mmlu_jurisprudence', 'jurisprudence',
     'The following are multiple choice questions (with answers) about jurisprudence.\n\n'),
    ('mmlu_logical_fallacies', 'logical_fallacies',
     'The following are multiple choice questions (with answers) about logical fallacies.\n\n'),
    ('mmlu_machine_learning', 'machine_learning',
     'The following are multiple choice questions (with answers) about machine learning.\n\n'),
    ('mmlu_management', 'management',
     'The following are multiple choice questions (with answers) about management.\n\n'),
    ('mmlu_marketing', 'marketing',
     'The following are multiple choice questions (with answers) about marketing.\n\n'),
    ('mmlu_medical_genetics', 'medical_genetics',
     'The following are multiple choice questions (with answers) about medical genetics.\n\n'),
    ('mmlu_miscellaneous', 'miscellaneous',
     'The following are multiple choice questions (with answers) about miscellaneous.\n\n'),
    ('mmlu_moral_disputes', 'moral_disputes',
     'The following are multiple choice questions (with answers) about moral disputes.\n\n'),
    ('mmlu_moral_scenarios', 'moral_scenarios',
     'The following are multiple choice questions (with answers) about moral scenarios.\n\n'),
    ('mmlu_nutrition', 'nutrition',
     'The following are multiple choice questions (with answers) about nutrition.\n\n'),
    ('mmlu_philosophy', 'philosophy',
     'The following are multiple choice questions (with answers) about philosophy.\n\n'),
    ('mmlu_prehistory', 'prehistory',
     'The following are multiple choice questions (with answers) about prehistory.\n\n'),
    ('mmlu_professional_accounting', 'professional_accounting',
     'The following are multiple choice questions (with answers) about professional accounting.\n\n'),
    ('mmlu_professional_law', 'professional_law',
     'The following are multiple choice questions (with answers) about professional law.\n\n'),
    ('mmlu_professional_medicine', 'professional_medicine',
     'The following are multiple choice questions (with answers) about professional medicine.\n\n'),
    ('mmlu_professional_psychology', 'professional_psychology',
     'The following are multiple choice questions (with answers) about professional psychology.\n\n'),
    ('mmlu_public_relations', 'public_relations',
     'The following are multiple choice questions (with answers) about public relations.\n\n'),
    ('mmlu_security_studies', 'security_studies',
     'The following are multiple choice questions (with answers) about security studies.\n\n'),
    ('mmlu_sociology', 'sociology',
     'The following are multiple choice questions (with answers) about sociology.\n\n'),
    ('mmlu_us_foreign_policy', 'us_foreign_policy',
     'The following are multiple choice questions (with answers) about us foreign policy.\n\n'),
    ('mmlu_virology', 'virology',
     'The following are multiple choice questions (with answers) about virology.\n\n'),
    ('mmlu_world_religions', 'world_religions',
     'The following are multiple choice questions (with answers) about world religions.\n\n'),
]


def _leaf(task_name, dataset_name, description):
    return {
        "task": task_name,
        "dataset_path": "hails/mmlu_no_train",
        "dataset_name": dataset_name,
        "dataset_kwargs": {"trust_remote_code": True},
        "test_split": "test",
        "fewshot_split": "dev",
        "fewshot_config": {"sampler": "first_n"},
        "doc_to_text": "{{question.strip()}}\nA. {{choices[0]}}\nB. {{choices[1]}}"
                       "\nC. {{choices[2]}}\nD. {{choices[3]}}\nAnswer:",
        "doc_to_target": "answer",
        "doc_to_choice": ["A", "B", "C", "D"],
        "description": description,
        "target_delimiter": " ",
        "metric_list": [{"metric": "acc", "aggregation": "mean",
                         "higher_is_better": True}],
        "output_type": "multiple_choice",
        "repeats": 1,
        "metadata": {"version": 1.0},
    }


GROUP = {
    "group": "mmlu",
    "task": [_leaf(*row) for row in SUBJECTS],
    "aggregate_metric_list": [{"metric": "acc", "weight_by_size": True}],
    "metadata": {"version": 2},
}
